skriv:
  url_template_lesforskriv: 'https://nvdbapiskriv.test.atlas.vegvesen.no/rest/v3/les/vegobjekt/{}/{}/{}'
  url_skriv:    'https://nvdbapiskriv.test.atlas.vegvesen.no/rest/v3/endringssett/'

login:
  user: 'jajens'
  miljo: 'testskriv'

gate:
  url_gater : 'https://nvdbapiles-v3.test.atlas.vegvesen.no/vegobjekter/538.json?inkluder=lokasjon,metadata,egenskaper&inkludergeometri=ingen'
  url_status : 'https://nvdbapiles-v3.test.atlas.vegvesen.no/status'
  url_statistikk : 'https://nvdbapiles-v3.test.atlas.vegvesen.no/vegobjekter/538/statistikk.json'
  url_template_enkeltgate : 'https://nvdbapiles-v3.test.atlas.vegvesen.no/vegobjekter/538/{}'
  url_template_kommune : 'https://nvdbapiles-v3.test.atlas.vegvesen.no/{}/{}'
  kommune_typeid : 536
  filnavn_template_apigater: 'nvdbapigater_{}.json'
  filnavn_template_gaterutensted: 'gaterutensted_{}.json'

log:
  loggnavn: 'Gatecrawler'
  loggfilnavn: 'gatecrawl.log'
  loggformat: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
