skriv:
  url_template_lesforskriv: 'https://nvdbapiskriv.atlas.vegvesen.no/rest/v3/les/vegobjekt/{}/{}/{}'
  url_skriv:    'https://nvdbapiskriv.atlas.vegvesen.no/rest/v3/endringssett/'

auth:
  url_login: 'https://www.vegvesen.no/ws/no/vegvesen/ikt/sikkerhet/aaa/'
  login_headers: {'content-type': 'application/json', 'Accept': 'application/json'}

login:
  user: 'arnesonf'

gate:
  url_gater : 'https://www.vegvesen.no/nvdb/api/v3/vegobjekter/538.json?inkluder=lokasjon,metadata,egenskaper&inkludergeometri=ingen'
  url_status : 'https://www.vegvesen.no/nvdb/api/v3/status'
  url_statistikk : 'https://www.vegvesen.no/nvdb/api/v3/vegobjekter/538/statistikk.json'
  url_template_enkeltgate : 'https://www.vegvesen.no/nvdb/api/v3/vegobjekter/538/{}'
  url_template_kommune : 'https://www.vegvesen.no/nvdb/api/v3/vegobjekter/{}/{}'
  kommune_typeid : 536
  filnavn_template_apigater: 'nvdbapigater_{}.json'
  filnavn_template_gaterutensted: 'gaterutensted_{}.json'

log:
  loggnavn: 'Gatecrawler'
  loggfilnavn: 'gatecrawl.log'
  loggformat: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
